#!/usr/bin/env ruby

Vagrant.configure(2) do |config|
  # disabling / changing silly defaults
  ## by default, there's not 'host_ip' restriction. So, anyone on your network
  ##  could ssh into the VM. Which is really, really stupid.
  config.vm.network :forwarded_port, guest: 22, host: 2222,
                    id: :ssh, host_ip: '127.0.0.1'
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # general config
  ## a patch a day keeps the botnet away
  config.vm.provision :shell, inline: <<-SHELL
      yum -y update
  SHELL

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
    vb.memory = "1024"
    config.ssh.password = 'vagrant'
    config.vm.box = "../packer/build/virtualbox-centos.box"
    config.vm.network :private_network, ip: "192.168.33.10"
  end

end
