
# setting up an ELK server as per:
# https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-elastic-stack.html
- hosts: monitor
  become: yes
  gather_facts: no
  tasks:
    #### Setting up repos and keys
    # TODO: validate I still need `apt-transport-https`
    - name: Ensure openjdk is installed and HTTPS works with apt.
      apt:
        name: [apt-transport-https, openjdk-17-jdk]
    - name: Install GPG so `apt_key` works.
      apt:
        name: gpg
    # TODO: `apt_key` module is deprecated. Debian has decided to "simplify" things by deprecating the `apt-key` command without providing a convenient command that fills the same niche.
    - name: Install the elastic.co repo key.
      apt_key:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
    - name: Install the elastic.co repo.
      apt_repository:
        repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
    #### Install elasticsearch
    - name: Install elasticsearch.
      apt:
        name: elasticsearch
    - name: Enable and start elasticsearch.
      systemd:
        name: elasticsearch
        state: started
        enabled: yes
