---
- hosts: all
  become: yes
  tasks:
    - copy:
        dest: /etc/salt/minion.d/99-master_name.conf
        content: "master: salt-infra\n"
    - service:
        name: salt-minion
        state: restarted

- hosts: salt-infra
  become: yes
  tasks:
    - copy:
        dest: /etc/salt/master
        mode: 0444
        content: |
          file_roots:
            base:
              - /srv/salt/states
              - /srv/salt/formulas/*
          pillar_roots:
            base:
              - /srv/salt/pillar
# TODO -- copy over states, formulas, and pillar
    - file:
        path: /srv/salt
        state: directory
    - synchronize:
        src: "../salt-configs/{{ item }}"
        dest: "/srv/salt"
        archive: no
        links: yes
        recursive: yes
        delete: yes
        perms: no
      with_items:
        - states
        - formulas
        - pillar
    - apt:
        name: salt-master
        state: present
    - service:
        name: salt-master
        state: running

- hosts: salt-infra
  become: yes
  tasks:
    - pause: seconds=10
    - command: salt-key --accept-all -y
    - command: salt '*' saltutil.sync_all
    - command: salt '*' saltutil.refresh_pillar
    - service:
        name: salt-master
        state: restarted




